In [2]:
import pandas as pd

In [3]:
TITANIC_URL = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [4]:
# seaborn.load_dataset('titanic') 실행
titanic = pd.read_csv(TITANIC_URL)

# head, info, describe 실행

In [5]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [7]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
# 생존자 필터링 및 성별 생존율 계산
survivors = titanic.loc[titanic['Survived'] == 1]
titanic[titanic['Survived'] == 1].groupby('Sex')['Survived'].mean()
titanic.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [ ]:
# isnull, sum으로 결측치 확인
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:

# fillna(median())로 age 처리
titanic['Age'] = titanic['Age'].fillna(titanic['Age'].mean())

In [ ]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# 등급별로 agg실행
titanic.groupby('Pclass').agg(생존율 = ('Survived', 'mean'), 요금 = ('Fare', 'mean'), 나이 = ('Age', 'mean'))

             생존율         요금         나이
Pclass
1       0.629630  84.154687  37.048118
2       0.472826  20.662183  29.866958
3       0.242363  13.675550  26.403259

In [ ]:
# 1등급 여성승객 이름 조회
titanic[(titanic['Pclass'] == 1) & (titanic['Sex'] == 'female')]['Name']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
11                              Bonnell, Miss. Elizabeth
31        Spencer, Mrs. William Augustus (Marie Eugenie)
52              Harper, Mrs. Henry Sleeper (Myna Haxtun)
                             ...
856           Wick, Mrs. George Dennick (Mary Hitchcock)
862    Swift, Mrs. Frederick Joel (Margaret Welles Ba...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
887                         Graham, Miss. Margaret Edith
Name: Name, Length: 94, dtype: str

In [ ]:
# 탑승항별 생존율 비교
titanic.groupby('Embarked').Survived.mean()

Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [ ]:
shoppingmall_url = 'mock_shopping_orders.csv'

In [ ]:
#데이터 생성 코드 실행
shoppingmall = pd.read_csv(shoppingmall_url)

In [ ]:
# 카테고리별 총매출 내림차순
shoppingmall.groupby('카테고리').agg(총매출 = ('총주문금액', 'sum')).sort_values('총매출', ascending=False)

           총매출
카테고리
의류     1461000
전기/전자  1332000
식품      917000
뷰티      640000

In [ ]:
shoppingmall.isnull().sum()

주문번호     0
사용자ID    0
주문일자     0
카테고리     0
상품명      0
단가       0
수량       0
총주문금액    0
주문상태     0
결제수단     0
dtype: int64

In [ ]:
# 카테고리 평균
shoppingmall['카테고리'].value_counts().mean()

np.float64(12.5)

In [ ]:
# price * quantity로 매출 컬럼 생성
shoppingmall['매출'] = shoppingmall['단가'] * shoppingmall['수량']

In [ ]:
# groupby + transform으로 결측치 채우기
shoppingmall['매출'] = shoppingmall.groupby('카테고리')['매출'].transform(lambda x: x.fillna(x.mean()))

In [ ]:
# nlargest(3) 또는 sort_values로 TOP 3 추출
shoppingmall.groupby('카테고리')['매출'].sum().nlargest(3)
#shoppingmall.groupby('카테고리')['매출'].sum().sort_values(ascending=False).head(6)

카테고리
의류       1461000
전기/전자    1332000
식품        917000
Name: 매출, dtype: int64