In [2]:
import pandas as pd

In [ ]:
# 데이터 생성 코드 실행 및 CSV 저장
shopping = pd.read_csv('mock_shopping_orders_with_nan.csv')

In [7]:
shopping

,주문번호,사용자ID,주문일자,카테고리,상품명,단가,수량,총주문금액,주문상태,결제수단,총매출
0,ORD-20260519-0001,user_1516,2026-05-05 20:26:00,의류,린넨 셔츠,45000.0,1,45000.0,배송완료,간편결제,45000.0
1,ORD-20260519-0002,user_1765,2026-05-03 01:51:00,식품,닭가슴살 팩 20입,35000.0,1,NaN,배송완료,간편결제,35000.0
2,ORD-20260519-0003,user_1611,2026-05-06 00:11:00,뷰티,보습 수분크림 50ml,28000.0,1,28000.0,배송완료,무통장입금,28000.0
3,ORD-20260519-0004,user_1128,2026-05-01 22:47:00,식품,유기농 더치커피 원액,18000.0,1,18000.0,배송완료,토스페이,18000.0
4,ORD-20260519-0005,user_1330,2026-05-16 03:41:00,의류,스트레이트 데님 팬츠,49000.0,1,NaN,배송완료,간편결제,49000.0
5,ORD-20260519-0006,user_1373,2026-05-17 17:20:00,뷰티,보습 수분크림 50ml,28000.0,2,56000.0,NaN,무통장입금,56000.0
6,ORD-20260519-0007,user_1414,2026-05-05 14:32:00,뷰티,비타민C 세럼,32000.0,1,32000.0,배송완료,토스페이,32000.0
7,ORD-20260519-0008,user_1658,2026-05-16 08:17:00,전기/전자,버티컬 무선 마우스,79000.0,1,79000.0,주문취소,간편결제,79000.0
8,ORD-20260519-0009,user_1795,2026-05-06 08:32:00,의류,린넨 셔츠,45000.0,1,45000.0,배송완료,신용카드,45000.0
9,ORD-20260519-0010,user_1942,2026-05-12 13:32:00,의류,오버핏 맨투맨 티셔츠,39000.0,2,78000.0,배송완료,신용카드,78000.0
10,ORD-20260519-0011,user_1638,2026-05-09 09:36:00,뷰티,보습 수분크림 50ml,28000.0,3,NaN,배송완료,무통장입금,84000.0
11,ORD-20260519-0012,user_1487,2026-05-07 09:29:00,식품,유기농 더치커피 원액,18000.0,1,18000.0,배송완료,무통장입금,18000.0
12,ORD-20260519-0013,user_1514,2026-05-18 23:33:00,식품,닭가슴살 팩 20입,NaN,1,35000.0,배송완료,무통장입금,NaN
13,ORD-20260519-0014,user_1093,2026-05-01 02:52:00,뷰티,보습 수분크림 50ml,28000.0,1,28000.0,배송중,신용카드,28000.0
14,ORD-20260519-0015,user_1680,2026-05-11 19:30:00,뷰티,비타민C 세럼,32000.0,1,NaN,배송완료,토스페이,32000.0
15,ORD-20260519-0016,user_1680,2026-05-16 23:17:00,의류,린넨 셔츠,45000.0,2,90000.0,배송완료,토스페이,90000.0
16,ORD-20260519-0017,user_1035,2026-05-13 04:29:00,의류,린넨 셔츠,45000.0,1,45000.0,배송중,무통장입금,45000.0
17,ORD-20260519-0018,user_1138,2026-05-13 06:01:00,의류,윈드브레이커 재킷,NaN,1,89000.0,배송완료,간편결제,NaN
18,ORD-20260519-0019,user_1284,2026-05-06 13:55:00,뷰티,비타민C 세럼,32000.0,2,64000.0,배송완료,간편결제,64000.0
19,ORD-20260519-0020,user_1129,2026-05-13 15:24:00,의류,린넨 셔츠,45000.0,1,45000.0,NaN,무통장입금,45000.0
20,ORD-20260519-0021,user_1162,2026-05-01 03:02:00,식품,단백질 보충 쉐이크,42000.0,4,168000.0,배송완료,신용카드,168000.0
21,ORD-20260519-0022,user_1228,2026-05-18 17:23:00,의류,오버핏 맨투맨 티셔츠,39000.0,1,NaN,배송중,신용카드,39000.0
22,ORD-20260519-0023,user_1297,2026-05-11 21:40:00,뷰티,올인원 자외선차단제,24000.0,1,24000.0,결제완료,무통장입금,24000.0
23,ORD-20260519-0024,user_1097,2026-05-18 04:30:00,뷰티,올인원 자외선차단제,24000.0,1,24000.0,주문취소,간편결제,24000.0
24,ORD-20260519-0025,user_1407,2026-05-01 00:49:00,식품,유기농 더치커피 원액,18000.0,1,18000.0,배송중,토스페이,18000.0
25,ORD-20260519-0026,user_1410,2026-05-05 09:52:00,뷰티,비타민C 세럼,32000.0,1,32000.0,배송완료,신용카드,32000.0
26,ORD-20260519-0027,user_1292,2026-05-01 23:13:00,식품,닭가슴살 팩 20입,35000.0,1,35000.0,배송중,토스페이,35000.0
27,ORD-20260519-0028,user_1713,2026-05-09 13:01:00,의류,린넨 셔츠,45000.0,2,90000.0,배송완료,간편결제,90000.0
28,ORD-20260519-0029,user_1500,2026-05-16 13:07:00,뷰티,비타민C 세럼,32000.0,1,32000.0,NaN,토스페이,32000.0
29,ORD-20260519-0030,user_1011,2026-05-03 00:43:00,식품,단백질 보충 쉐이크,42000.0,1,42000.0,배송완료,토스페이,42000.0
30,ORD-20260519-0031,user_1891,2026-05-04 16:47:00,뷰티,비타민C 세럼,NaN,2,NaN,배송완료,간편결제,NaN
31,ORD-20260519-0032,user_1135,2026-05-13 10:16:00,식품,닭가슴살 팩 20입,35000.0,4,140000.0,결제완료,무통장입금,140000.0
32,ORD-20260519-0033,user_1048,2026-05-16 05:43:00,전기/전자,고속 충전 보조배터리,35000.0,1,35000.0,주문취소,간편결제,35000.0
33,ORD-20260519-0034,user_1885,2026-05-10 13:40:00,전기/전자,기계식 게이밍 키보드,129000.0,1,NaN,결제완료,신용카드,129000.0
34,ORD-20260519-0035,user_1334,2026-05-18 17:44:00,뷰티,비타민C 세럼,32000.0,1,32000.0,배송중,신용카드,32000.0
35,ORD-20260519-0036,user_1918,2026-05-13 16:58:00,전기/전자,무선 노이즈캔슬링 헤드폰,199000.0,1,199000.0,배송중,신용카드,199000.0
36,ORD-20260519-0037,user_1993,2026-05-03 21:39:00,식품,단백질 보충 쉐이크,42000.0,4,NaN,배송완료,무통장입금,168000.0
37,ORD-20260519-0038,user_1518,2026-05-03 00:34:00,식품,닭가슴살 팩 20입,35000.0,1,35000.0,배송완료,토스페이,35000.0
38,ORD-20260519-0039,user_1962,2026-05-07 02:59:00,식품,유기농 더치커피 원액,18000.0,1,18000.0,배송완료,신용카드,18000.0
39,ORD-20260519-0040,user_1151,2026-05-16 00:59:00,뷰티,비타민C 세럼,32000.0,3,96000.0,배송중,무통장입금,96000.0
40,ORD-20260519-0041,user_1309,2026-05-16 03:24:00,의류,오버핏 맨투맨 티셔츠,NaN,5,195000.0,배송완료,토스페이,NaN
41,ORD-20260519-0042,user_1029,2026-05-11 08:02:00,뷰티,보습 수분크림 50ml,28000.0,1,28000.0,배송완료,토스페이,28000.0
42,ORD-20260519-0043,user_1077,2026-05-19 13:02:00,전기/전자,버티컬 무선 마우스,NaN,1,79000.0,주문취소,신용카드,NaN
43,ORD-20260519-0044,user_1488,2026-05-04 10:19:00,식품,닭가슴살 팩 20입,35000.0,4,140000.0,배송완료,신용카드,140000.0
44,ORD-20260519-0045,user_1972,2026-05-03 15:17:00,의류,린넨 셔츠,45000.0,1,45000.0,배송완료,신용카드,45000.0
45,ORD-20260519-0046,user_1444,2026-05-19 05:27:00,식품,닭가슴살 팩 20입,35000.0,1,35000.0,배송중,무통장입금,35000.0
46,ORD-20260519-0047,user_1432,2026-05-07 07:21:00,식품,유기농 더치커피 원액,18000.0,1,18000.0,NaN,토스페이,18000.0
47,ORD-20260519-0048,user_1486,2026-05-09 17:47:00,전기/전자,고속 충전 보조배터리,35000.0,5,175000.0,배송완료,간편결제,175000.0
48,ORD-20260519-0049,user_1595,2026-05-03 05:29:00,전기/전자,버티컬 무선 마우스,79000.0,1,79000.0,배송완료,무통장입금,79000.0
49,ORD-20260519-0050,user_1980,2026-05-02 00:57:00,전기/전자,버티컬 무선 마우스,79000.0,1,79000.0,배송완료,신용카드,79000.0

In [6]:
# price * quantity 로 매출 컬럼 생성
shopping['총매출'] = shopping['단가'] * shopping['수량']
shopping['총매출']

0      45000.0
1      35000.0
2      28000.0
3      18000.0
4      49000.0
5      56000.0
6      32000.0
7      79000.0
8      45000.0
9      78000.0
10     84000.0
11     18000.0
12         NaN
13     28000.0
14     32000.0
15     90000.0
16     45000.0
17         NaN
18     64000.0
19     45000.0
20    168000.0
21     39000.0
22     24000.0
23     24000.0
24     18000.0
25     32000.0
26     35000.0
27     90000.0
28     32000.0
29     42000.0
30         NaN
31    140000.0
32     35000.0
33    129000.0
34     32000.0
35    199000.0
36    168000.0
37     35000.0
38     18000.0
39     96000.0
40         NaN
41     28000.0
42         NaN
43    140000.0
44     45000.0
45     35000.0
46     18000.0
47    175000.0
48     79000.0
49     79000.0
Name: 총매출, dtype: float64

In [18]:
#groupby + transform으로 결측치 채우기
shopping['총주문금액'] = shopping['총주문금액'].fillna(shopping['단가'] * shopping['수량'])
shopping['주문상태'] = shopping['주문상태'].fillna('확인불가')
shopping['총매출'] = shopping.groupby('카테고리')['단가'].transform(lambda x : x.fillna(x.mean()))

In [19]:
shopping.isnull().sum()

주문번호     0
사용자ID    0
주문일자     0
카테고리     0
상품명      0
단가       0
수량       0
총주문금액    0
주문상태     0
결제수단     0
총매출      0
dtype: int64

In [20]:
# nlargest(3) 또는 sort_values로 TOP 3 추출
shopping.sort_values('총매출', ascending=False).head(3)

,주문번호,사용자ID,주문일자,카테고리,상품명,단가,수량,총주문금액,주문상태,결제수단,총매출
35,ORD-20260519-0036,user_1918,2026-05-13 16:58:00,전기/전자,무선 노이즈캔슬링 헤드폰,199000.000000,1,199000.000000,배송중,신용카드,199000.000000
33,ORD-20260519-0034,user_1885,2026-05-10 13:40:00,전기/전자,기계식 게이밍 키보드,129000.000000,1,103571.428571,결제완료,신용카드,129000.000000
42,ORD-20260519-0043,user_1077,2026-05-19 13:02:00,전기/전자,버티컬 무선 마우스,90714.285714,1,79000.000000,주문취소,신용카드,90714.285714

In [ ]:
# 카테고리별 총매출 내림차순
shopping.groupby('카테고리').agg(총매출 = ('총주문금액', 'sum')).sort_values('총매출', ascending=False)

                 총매출
카테고리
의류     920400.000000
식품     830769.230769
전기/전자  828571.428571
뷰티     595000.000000

In [ ]:
# 고객별 총주문금액 top3
shopping.groupby('사용자ID').agg({'총주문금액': 'sum'}).sort_values('총주문금액', ascending=False).head(3)

                   총주문금액
사용자ID
user_1011   42000.000000
user_1029   28000.000000
user_1035   45000.000000
user_1048   35000.000000
user_1077   79000.000000
user_1093   28000.000000
user_1097   24000.000000
user_1128   18000.000000
user_1129   45000.000000
user_1135  140000.000000
user_1138   89000.000000
user_1151   96000.000000
user_1162  168000.000000
user_1228   76700.000000
user_1284   64000.000000
user_1292   35000.000000
user_1297   24000.000000
user_1309  195000.000000
user_1330   76700.000000
user_1334   32000.000000
user_1373   56000.000000
user_1407   18000.000000
user_1410   32000.000000
user_1414   32000.000000
user_1432   18000.000000
user_1444   35000.000000
user_1486  175000.000000
user_1487   18000.000000
user_1488  140000.000000
user_1500   32000.000000
user_1514   35000.000000
user_1516   45000.000000
user_1518   35000.000000
user_1595   79000.000000
user_1611   28000.000000
user_1638   39666.666667
user_1658   79000.000000
user_1680  129666.666667
user_1713   90000.000000
user_1765   55384.615385
user_1795   45000.000000
user_1885  103571.428571
user_1891   39666.666667
user_1918  199000.000000
user_1942   78000.000000
user_1962   18000.000000
user_1972   45000.000000
user_1980   79000.000000
user_1993   55384.615385